### ISSUE TITLE
`<cr>` could act like gf when it is over a file name?

### ISSUE THREAD

**Issue by voyeg3r** [sam4llis/nvim-lua-gf#1]
I am trying to make Enter triggers gf when over file names, just for the chalkenge and fun. Can you help me with that?

It seems that Mason has a function is_file or isFile, i am not sure, but it could gives a return to a function like

```
local filename = vim.fn.expand("<cfile>")
return (is_file(filename) and 'gf' or '<cr>'
```

I have made some research but did not find a perfect "isfile" function

I also know that vim.keyma.set must have expr=true to retur literal keys like` gf `or `<cr>`

**Comment by sam4llis** [comment]
Hi, apologies if I’ve confused what you want, but could you simply remap your enter key to ‘gf’?

```vimscript
nnoremap <CR> gf
```
